apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.nginx-app.fullname" . }}-config
  labels:
    {{- include "helm.nginx-app.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.env.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}

