{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "helm.nginx-app.fullname" . }}
spec:
  host: {{ include "helm.nginx-app.fullname" . }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  {{- end }}