{{- $istio := .Values.istio | default dict -}}
{{- $dr := $istio.destinationRule | default dict -}}
{{- if ($dr.enabled | default false) -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "nginx-app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
spec:
  host: {{ include "nginx-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: {{ $dr.tlsMode | default "DISABLE" | quote }}
{{- end }}