apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-template
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

     location /api/env {
       default_type application/json;
       return 200 "{\"APP_ENV\":\"$APP_ENV\",\"WELCOME_MSG\":\"$WELCOME_MSG\",\"DB_USER\":\"$DB_USER\"}";
      }

     location /health {
       default_type text/plain;
       return 200 "ok\n";
      }
}
